version: "3"
services:
  db:
    image: postgres:13
    container_name: spotimaps-db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  spotimaps-back:
    container_name: spotimaps-back
    build: .
    ports:
      - 5000:4002
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres: